[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "buttonless"

[font]
normal.family = "SFMono Nerd Font"
normal.style = "Regular"
size = 18

[colors]
# manually setting background to match nvim
# used `:hi Normal` and used guibg value
primary.background = "#222436"
